version: '3'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  web:
    # Django Channels를 실행하는 서비스
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./chat:/usr/src/app/chat
    ports:
      - "8000:8000"
    depends_on:
      - redis
