# Generated by Django 4.2.7 on 2023-11-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_auto_20231129_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="post/images/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="weather",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
