# Generated by Django 4.2.7 on 2023-11-30 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatmessage_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="user",
            new_name="username",
        ),
    ]
