# Generated by Django 4.2.7 on 2023-12-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_chatroom_alter_chatmessage_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="room_name",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
    ]
