# Generated by Django 4.2.7 on 2023-12-02 01:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0009_chatroom_remove_chatmessage_room_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChatMessage",
            new_name="Chat",
        ),
    ]
